language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
install:
 - python setup.py develop
 - pip install -U pytest pytest-cov coveralls
 - pip install -r requirements.txt
script:
  py.test --cov skosprovider_rdf --cov-report term-missing tests
after_success:
  coveralls
